import type { Metadata } from "next";
import "./globals.css";
import HydrationGuard from "@/components/HydrationGuard";

export const metadata: Metadata = {
  title: "ClinicPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <HydrationGuard>{children}</HydrationGuard>
      </body>
    </html>
  );
}
